-- Activación de extensiones necesarias para Osmi
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS tablefunc;
--CREATE EXTENSION IF NOT EXISTS hypopg;
--CREATE EXTENSION IF NOT EXISTS pg_cron;
